# Generated by Django 6.0.3 on 2026-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuentry_product_remove_saleitem_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
