# Generated by Django 6.0.3 on 2026-04-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_globalsetting_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='table_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
