# Generated by Django 6.0.3 on 2026-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sale_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
