# Generated by Django 6.0.3 on 2026-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('km_price', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('max_km', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], unique=True)),
                ('opening_time', models.TimeField(default='20:00')),
                ('closing_time', models.TimeField(default='00:00')),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
