# Generated by Django 6.0.3 on 2026-04-07 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentry',
            name='active_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='active_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
