# Generated by Django 6.0.3 on 2026-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_menuentry_active_friday_menuentry_active_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_webmail',
            field=models.BooleanField(default=False),
        ),
    ]
