# Generated by Django 6.0.3 on 2026-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_actionlog_timestamp_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysetting',
            name='marquee_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
