# Generated by Django 6.0.3 on 2026-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventoryitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
    ]
