# Generated by Django 6.0.3 on 2026-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_inventoryitem_min_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentry',
            name='category',
        ),
    ]
