# Generated by Django 6.0.3 on 2026-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_prepared',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_use_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
