# Generated by Django 6.0.3 on 2026-04-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_sale_is_prepared_userprofile_can_use_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
