# Generated by Django 6.0.3 on 2026-04-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sale_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_delivered',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
