# Generated by Django 6.0.3 on 2026-04-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_sale_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
