# Generated by Django 6.0.3 on 2026-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sale_prepared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
