# Generated by Django 6.0.3 on 2026-04-12 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_sale_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='Cantidad del ítem de inventario consumida por cada unidad vendida del producto.', max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_products', to='api.inventoryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='api.product')),
            ],
            options={
                'ordering': ['inventory_item__name'],
                'unique_together': {('product', 'inventory_item')},
            },
        ),
    ]
