# Generated by Django 6.0.3 on 2026-04-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_product_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stock_deducted',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si ya se descontó la materia prima del inventario al completar este pedido.'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste Manual')], db_index=True, max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.CharField(help_text="Ej: 'Venta #42', 'Compra proveedor', 'Ajuste manual'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detalle adicional del movimiento.', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.inventoryitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='api.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='api.sale')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
