# Generated by Django 6.0.3 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_stock_deducted_and_inventory_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='pack_name',
            field=models.CharField(blank=True, help_text="Nombre del contenedor (ej: 'cajas', 'packs')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cuántas unidades base trae cada pack', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='unidades', help_text='Unidad base (ej: gramos, unidades)', max_length=50),
        ),
    ]
