# Generated by Django 6.0.3 on 2026-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_inventory_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='has_weight',
            field=models.BooleanField(default=False, help_text='¿La unidad tiene un peso/volumen asignado?'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso/Volumen de 1 unidad base', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='measurement_unit',
            field=models.CharField(default='unidades', help_text="Unidad lógica de descuento (ej: 'unidades', 'g', 'kg', 'ml', 'l')", max_length=20),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad del ítem de inventario consumida por cada unidad vendida del producto.', max_digits=10),
        ),
    ]
