# Generated by Django 6.0.3 on 2026-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_inventory_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='sub_unit_name',
            field=models.CharField(blank=True, help_text='Ej: fetas, unidades', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sub_units_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Cuántas sub-unidades trae cada unidad base', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='use_sub_units',
            field=models.BooleanField(default=False, help_text='¿La unidad tiene un desglose interno en unidades?'),
        ),
    ]
