# Generated by Django 6.0.3 on 2026-04-13 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_inventoryitem_sub_unit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='sale',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida (Ajuste)'), ('ADJ', 'Ajuste Manual')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(help_text="Ej: 'Compra proveedor', 'Ajuste manual'", max_length=255),
        ),
        migrations.CreateModel(
            name='InventoryDailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumptions', to='api.inventoryitem')),
            ],
            options={
                'ordering': ['-date', 'inventory_item__name'],
                'unique_together': {('inventory_item', 'date')},
            },
        ),
    ]
